name: test

on:
  workflow_run:
    workflows: ["Ejercicio Cabrita"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Selecciona el entorno de despliegue'
        required: true
        type: choice
        options:
          - desarrollo
          - prueba
          - produccion
      version:
        description: 'Especifica la versión del software'
        required: true
        type: choice
        options:
          - '1.0.0'
          - '1.1.0'
          - '2.0.0'

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Pasarle un secreto de github
        env: 
            secretito: ${{ secrets.SECRETO }}
        run: |
          echo "$secretito"
